{
 "title": "Status Check Global Websites",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "World Latency Map",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"blackbox_.*\"}"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "target",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "stat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  }
 ]
}